services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: flowmind-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: flowmind
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - flowmind-network

  # Redis for caching and background tasks
  redis:
    image: redis:7.2-alpine
    container_name: flowmind-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flowmind-network

  # Backend API (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flowmind-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/flowmind?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/venv
    depends_on:
      - mongodb
      - redis
    networks:
      - flowmind-network
    env_file:
      - ./backend/.env

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flowmind-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - flowmind-network
    env_file:
      - ./frontend/.env

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: flowmind-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - flowmind-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  flowmind-network:
    driver: bridge
